### ISSUE TITLE
Warmer event randomly not detected in lambda

### ISSUE THREAD

**Issue by robinth91** [jeremydaly/lambda-warmer#10]
One of our lambdas randomly doesn't detect the event as a `warmer` event and proceed further which breaks our code (it happens 2-5 times a day).

Our code looks like below:
```
module.exports.execute = async (event, context, callback) => {
  // Warming up the lambda.
  if (await warmer(event)) {
    console.log('Warming up the lambda');
    return;
  }

  // Other code
}
```

We use serverless to schedule the warmer.

```
- schedule:
    name: ${self:service}-${self:provider.region}-${self:provider.stage}-warmer-lambda
    rate: rate(5 minutes)
    enabled: ${self:custom.warmup.enabled.${self:custom.config.environment}}
    input:
      warmer: true
      concurrency: 3
```

Using atleast `v3.5.0` of the`lambda-warmer`.
node version `8.10.0`
